language: node_js
node_js:
  - "7"
install:
  - git clone --recurse-submodules https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT
  - npm install
  # Skills matrix START
  - cd apps/skills-matrix-api-node
  - git clone https://github.com/L3bowski/skills-matrix-client-jquery
  - rm -rf public/
  - mv skills-matrix-client-jquery/app public
  - rm -rf skills-matrix-client-jquery
  - cd ../..
  # Skills matrix END
  # Vue personal page START
  - cd apps/vue-personal-page
  - npm install
  - npm run build
  - rm -rf node_modules
  - cd ../..
  # Vue personal page END
  # Webjack START
  - cd apps/webjack
  - git clone https://github.com/L3bowski/webjack-ui
  - cd webjack-ui
  - npm install
  - npm run build
  - cd ..
  - mv webjack-ui/dist public
  - rm -rf webjack-ui
  - cd ../..
  # Webjack END
deploy:
  - provider: heroku
    app:
      development: $heroku_app_name
    api_key:
      secure: $heroku_api_key
  - provider: azure_web_apps
    username: $azure_deployment_user
    password: $azure_deployment_password
    site: $azure_deployment_site
    on:
      branch: development
