language: node_js
node_js:
  - "7"
deploy:
  provider: heroku
  app:
    development: modena
  api_key:
    secure: $heroku_api_key
  run:
    - "cd apps"
    - "git clone https://github.com/L3bowski/jokify"
    - restart